import { STORE_IDENTITY as nap } from "./storeIdentity";

export const gbpLocation = {
  storeName: nap.name,
  domain: nap.domain,
  city: nap.addressLocality,
  province: nap.addressRegion,
  country: nap.addressCountry,
  slug: "weed-dispensary-mississauga",
  address: nap.addressDisplay,
  streetAddress: nap.streetAddress,
  postalCode: nap.postalCode,
  phone: nap.phoneDisplay,
  phoneIntl: nap.phoneIntl,
  neighborhood: nap.neighborhood,
  nearbyAreas: ["Lakeshore Rd W", "Clarkson", "Mississauga", "Port Credit", "Clarkson GO", "Lorne Park", "MiWay"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: String(nap.latitude),
  longitude: String(nap.longitude),
  hours: ["Open 24 Hours"],
  seoTitle: "Weed Dispensary in Mississauga | High Coastal Cannabis",
  metaDescription: "High Coastal Cannabis is open 24 hours at 1720 Lakeshore Rd W in Mississauga. Adults 19+ can explore flower, pre-rolls, edibles, vapes and concentrates. Call +1 (289) 815-5222.",
  localLandmarks: ["Lakeshore Rd W", "Clarkson", "Mississauga"],
  introVariant: "High Coastal Cannabis is a local weed dispensary at 1720 Lakeshore Rd W in Mississauga. Adults 19+ can browse flower tiers and category pages for pre-rolls, edibles, vapes, concentrates, and accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Clarkson / Lakeshore district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Plaza parking lot is available for customers",
  transitNote: "Steps from Clarkson GO Station and accessible by local MiWay routes.",
  sectionTitle: "Serving Customers Near Clarkson and Mississauga"
};
