export const gbpLocation = {
  storeName: "High Coastal Cannabis",
  domain: "www.highcoastalcannabis.com",
  city: "Mississauga",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-mississauga",
  address: "1720 Lakeshore Rd W, Mississauga, ON L5J 1J5",
  streetAddress: "1720 Lakeshore Rd W",
  postalCode: "L5J 1J5",
  phone: "(289) 401-7550",
  phoneIntl: "+12894017550",
  neighborhood: "Clarkson / Lakeshore",
  nearbyAreas: ["Lakeshore Rd W", "Clarkson", "Mississauga", "Port Credit", "Clarkson GO", "Lorne Park", "MiWay"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.5177",
  longitude: "-79.6220",
  hours: ["Open 24 Hours"],
  seoTitle: "High Coastal Cannabis | Weed Dispensary in Mississauga",
  metaDescription: "High Coastal Cannabis is a local weed dispensary in Mississauga offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Lakeshore Rd W", "Clarkson", "Mississauga"],
  introVariant: "High Coastal Cannabis is a local weed dispensary at 1720 Lakeshore Rd W in Mississauga. Adults 19+ can browse flower tiers and category pages for pre-rolls, edibles, vapes, concentrates, and accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Clarkson / Lakeshore district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Plaza parking lot is available for customers",
  transitNote: "Steps from Clarkson GO Station and accessible by local MiWay routes.",
  sectionTitle: "Serving Customers Near Clarkson and Mississauga"
};
