// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "High Coastal Cannabis",
  domain: "highcoastalcannabis.com",
  city: "Mississauga",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-mississauga",
  address: "1720 Lakeshore Rd W, Mississauga, ON L5J 1J5",
  streetAddress: "1720 Lakeshore Rd W",
  postalCode: "L5J 1J5",
  phone: "(289) 401-7550",
  phoneIntl: "+12894017550",
  neighborhood: "Clarkson / Lakeshore",
  nearbyAreas: ["Lakeshore Rd W", "Clarkson", "Mississauga", "Port Credit", "Clarkson GO", "Lorne Park", "MiWay"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=1720+Lakeshore+Rd+W,+Mississauga,+ON+L5J+1J5",
  mapEmbedUrl: "https://maps.google.com/maps?q=High%20Coastal%20Cannabis%201720%20Lakeshore%20Rd%20W%2C%20Mississauga%2C%20ON%20L5J%201J5&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.5177",
  longitude: "-79.6220",
  hours: ["Open 24 Hours"],
  seoTitle: "High Coastal Cannabis | Weed Dispensary in Mississauga",
  metaDescription: "High Coastal Cannabis is a local weed dispensary in Mississauga offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Lakeshore Rd W", "Clarkson", "Mississauga"],
  introVariant: "If you are searching for a reliable weed dispensary in Mississauga, High Coastal Cannabis at 1720 Lakeshore Rd W is your go-to destination. We serve adults 19+ with a vast selection of weed products including cannabis flower, pre-rolls, edibles, THC vapes, shatter, and CBD oils. Serving customers near Clarkson / Lakeshore and surrounding communities like Clarkson, our cannabis store and weed shop is focused on quality and convenience.",
  neighborhoodDescription: "Located in the vibrant Clarkson / Lakeshore district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Plaza parking lot is available for customers",
  transitNote: "Steps from Clarkson GO Station and accessible by local MiWay routes.",
  sectionTitle: "Serving Customers Near Clarkson and Mississauga"
};
